
//-------------Users
GET http://localhost:4000/api/users

###


GET http://localhost:4000/api/users/allUsers

###

DELETE http://localhost:4000/api/users/logOut


###

POST http://localhost:4000/api/users/register
Content-Type: application/json

{
    "userName": "Oliver",  
    "passWord": "5aAf4CUv",
    "rePassword": "sadasdsa"
}


###

POST http://localhost:4000/api/users/login
Content-Type: application/json

{
    "userName": "Petter",  
    "passWord": "Hej123"
}

###

GET http://localhost:4000/api/users/loggedIn

###
//-----------Tweets
GET http://localhost:4000/api/posts

###

GET http://localhost:4000/api/posts/2

###


POST http://localhost:4000/api/posts/
Content-Type: application/json

{   
    "tweet": "tweet 3"
}

###

DELETE http://localhost:4000/api/posts/6081436157ed521f0cb098d5

###


PUT http://localhost:4000/api/posts/608140a3a6f3993a48cc3519
Content-Type: application/json

{
    "tweet": "Hoppar på krykor"
}