
//-------------Users
GET http://localhost:4000/api/users

###


GET http://localhost:4000/api/users/allUsers

###

DELETE http://localhost:4000/api/users/logOut


###

POST http://localhost:4000/api/users/register
Content-Type: application/json

{
    "userName": "Oliver",  
    "passWord": "5aAf4CUv",
    "rePassword": "sadasdsa"
}


###

POST http://localhost:4000/api/users/login
Content-Type: application/json

{
    "userName": "Hampus",  
    "passWord": "12341234"
}

###

//-----------Tweets
GET http://localhost:4000/api/posts

###

GET http://localhost:4000/api/posts/2

###


POST http://localhost:4000/api/posts/
Content-Type: application/json

{   
    "name": "Josefin Malmqvist",
    "tweet": "tweet 3"
}

###

DELETE http://localhost:4000/api/posts/608013ccc871533b90f0ddbb

###


PUT http://localhost:4000/api/posts/60801f297cc42b49d86cc4ec
Content-Type: application/json

{
    "name": "Felix",
    "tweet": "Hoppar på krykor"
}