
GET http://localhost:4000/api/users

###


GET http://localhost:4000/api/users/allUsers

###

GET http://localhost:4000

###

POST http://localhost:4000/api/users/register
Content-Type: application/json

{
    "name": "Oliver", 
    "age": 25, 
    "password": "12341234"
}


###

POST http://localhost:4000/api/users/login
Content-Type: application/json

{
    "name": "Oliver", 
    "age": 25, 
    "password": "12341234"
}

GET http://localhost:4000/api/posts/tweets

###¨

GET http://localhost:4000/api/posts/tweets/2

###


POST http://localhost:4000/api/posts/tweets
Content-Type: application/json

{
    "tweet": "tweet 3"
}

###

DELETE http://localhost:4000/api/posts/tweets/3

###


PUT http://localhost:4000/api/posts/tweets/2
Content-Type: application/json

{
    "tweet": "tittar på tv"
}

